---
controller_execution_environments:
  - name: "Cloud Operations EE"
    organization: "Cloud Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/cloud_ee:latest"
    pull: "always"
  - name: "IDM Operations EE"
    organization: "IDM Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/idm_ee:latest"
    pull: "always"
  - name: "ITSM Operations EE"
    organization: "ITSM Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/itsm_ee:latest"
    pull: "always"
  - name: "Network Operations EE"
    organization: "Network Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/network_ee:latest"
    pull: "always"
  - name: "Satellite Operations EE"
    organization: "Patching Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/satellite_ee:latest"
    pull: "always"
  - name: "Linux Operations EE"
    organization: "Server Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/day2_ee:latest"
    pull: "always"
  - name: "Windows Operations EE"
    organization: "Server Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/windows_ee:latest"
    pull: "always"
  - name: "AAP Config as Code EE"
    organization: "SuperAdmin"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/aap_casc_ee:latest"
    pull: "always"
  - name: "OCP Virtualization EE"
    organization: "Virtualization Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/ocpv_ee:latest"
    pull: "always"
  - name: "Web Operations EE"
    organization: "Web Operations"
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/web_ee:latest"
    pull: "always"
  - name: "Minimal execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:348e84ee0f325ab686e84a5eedace008e14d4b5f36e1c9bc1fc727c6afc4c957"
    pull: ""
  - name: "Default execution environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:da9d6d4ed8b2b86ca7ef6cd0eeaa996c1e2fe7427f0d31baf7a576248940295d"
    pull: ""
  - name: "Control Plane Execution Environment"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:da9d6d4ed8b2b86ca7ef6cd0eeaa996c1e2fe7427f0d31baf7a576248940295d"
    pull: ""
  - name: "Patch Operations EE"
    organization:  # Leave this empty organization to let the object_diff role to work properly
    image: "production-aap.apps.ocp.bk.lab/homelab_ees/patch_ee:latest"
    pull: "always"
...